#!/bin/bash
sleep 60s


  if composer card list -c PeerAdmin@hlfv1 > /dev/null; then
      composer card delete -c PeerAdmin@hlfv1
  fi

  composer card create -p ./connection_admin.json -u PeerAdmin -c ./cert  -k ./key  -r PeerAdmin -r ChannelAdmin --file ./PeerAdmin@hlfv1.card
  composer card import --file ./PeerAdmin@hlfv1.card
  rm ./PeerAdmin@hlfv1.card

  composer network install -c PeerAdmin@hlfv1  -a ./bond-network.bna



composer network start -c PeerAdmin@hlfv1   -n bond-network  -A admin  -S adminpw -f admin@bond-network.card -V 0.2.6

composer card import --file admin@bond-network.card

composer network ping --card admin@bond-network

rm ./admin@bond-network.card

nohup composer-rest-server -c admin@bond-network  -p 5555 &


sleep 36000000s
